# APIs

a) public apis - rapidapi.com <br>
b) private apis - twitter api

In [1]:
import requests
import json
from datetime import datetime
import pandas as pd


print(requests.__version__)

2.27.1

In [2]:
response = requests.get('https://ashokappesoc.com')
print(response.status_code) #status_code
print(type(response))
# print(response.content) #beautifulSoup for looking at html

200
<class 'requests.models.Response'>

In [3]:
# open-notify.com
#different endpoints poin tto different information

response = requests.get('http://api.open-notify.org/astros.json')
print(response.status_code)
print(response.content)

result = json.loads(response.content)
print(type(result))

200
b'{"number": 10, "people": [{"name": "Oleg Artemyev", "craft": "ISS"}, {"name": "Denis Matveev", "craft": "ISS"}, {"name": "Sergey Korsakov", "craft": "ISS"}, {"name": "Kjell Lindgren", "craft": "ISS"}, {"name": "Bob Hines", "craft": "ISS"}, {"name": "Samantha Cristoforetti", "craft": "ISS"}, {"name": "Jessica Watkins", "craft": "ISS"}, {"name": "Cai Xuzhe", "craft": "Tiangong"}, {"name": "Chen Dong", "craft": "Tiangong"}, {"name": "Liu Yang", "craft": "Tiangong"}], "message": "success"}'
<class 'dict'>

In [4]:
print("Total number of people in space rn = ", result['number'])
names = [name['name'] for name in result['people']]
print("\nNames of people in space rn :", names)
crafts = [craft['craft'] for craft in result['people']]
print("\nassociated crafts :", crafts)

Total number of people in space rn =  10

Names of people in space rn : ['Oleg Artemyev', 'Denis Matveev', 'Sergey Korsakov', 'Kjell Lindgren', 'Bob Hines', 'Samantha Cristoforetti', 'Jessica Watkins', 'Cai Xuzhe', 'Chen Dong', 'Liu Yang']

associated crafts : ['ISS', 'ISS', 'ISS', 'ISS', 'ISS', 'ISS', 'ISS', 'Tiangong', 'Tiangong', 'Tiangong']

In [5]:
response = requests.get('http://api.open-notify.org/iss-now.json')
print(response.status_code)
print(response.text)

result = response.json() #instead of load

print(result.keys())

200
{"iss_position": {"longitude": "111.2267", "latitude": "-18.0094"}, "timestamp": 1656055810, "message": "success"}
dict_keys(['iss_position', 'timestamp', 'message'])

In [6]:
print(f'Latitude and Longitide value', result['iss_position']['latitude'],result['iss_position']['longitude'])
time  = datetime.fromtimestamp(result['timestamp'])

print("current time of the data ", time)

Latitude and Longitide value -18.0094 111.2267
current time of the data  2022-06-24 13:00:10

In [7]:
# http://api.open-notify.org/iss-pass.json

parameters = {
    "lat":12.4654,
    "lon":74.5135
}

url = 'http://api.open-notify.org/iss-pass.json'

response = requests.get(url=url,params=parameters)
# print(response.text)

result = response.json()

print(result)

{'message': 'success', 'request': {'altitude': 100, 'datetime': 1656055812, 'latitude': 12.4654, 'longitude': 74.5135, 'passes': 5}, 'response': [{'duration': 607, 'risetime': 1656060558}, {'duration': 577, 'risetime': 1656102658}, {'duration': 584, 'risetime': 1656108449}, {'duration': 432, 'risetime': 1656138347}, {'duration': 646, 'risetime': 1656144049}]}

In [8]:
list_times = [datetime.fromtimestamp(time['risetime']) for time in result['response']]
for time in list_times:
    print(time)

2022-06-24 14:19:18
2022-06-25 02:00:58
2022-06-25 03:37:29
2022-06-25 11:55:47
2022-06-25 13:30:49

## Weather API

In [18]:
url = 'https://api.openweathermap.org/data/2.5/forecast'

parameters={
    'q':'Delhi,India',
    'APPID':'1960401d79b51d8c3be286b9463a081b',
    'units':'metric'
}

response = requests.get(url=url,params=parameters)

result = response.json()

# print(result)

In [19]:
# info = result['list']
# # print(info)
# dict = {}
# list = []

# for item in info:
#     try:
#         dict['Time']=datetime.fromtimestamp(item['dt'])
#         dict['Temp']=item['main']['temp']
#         dict['Pressure']=item['main']['grnd_level'] #atmospheric pressure at grnd level
#         dict['Humidity']=item['main']['humidity']
#         dict['Cloud_description']=item['weather'][0]['description']
#         dict['Wind_speed']=item['wind']['speed']
#         dict['Wind_direction']=item['wind']['deg']
#         dict['Visibility']=item['visibiity']
#         try:
#             dict['Rain']=item['rain']
#         except:
#             dict['Rain'] = ''
#         list.append(dict)
#     except:
#         pass
    

# print(list)

# NOT WORING FOR SOME REASON

In [20]:
print(result['message'])
print(result['cnt'])
info=result['list']
# print(info)

dict={}
list=[]

for item in info:
    dict = {}
    try:
        dict['Time']=datetime.fromtimestamp(item['dt'])
        dict['Temp']=item['main']['temp']
        dict['Pressure']=item['main']['pressure']
        dict['Ground_level']=item['main']['grnd_level'] # atmospheric pressure at ground level 
        dict['Humidity']=item['main']['humidity']
        dict['Cloud_description']=item['weather'][0]['description']
        dict['Wind']=item['wind']['speed']
        dict['Wind_direction']=item['wind']['deg']
        dict['Visibility']=item['visibility']
        try:
            dict['Rain']=item['rain']
        except:
            dict['Rain']='None'
        list.append(dict)
        # print(dict)
        # print(list[-1])
    except:
        pass 
    
# print(list)

df = pd.DataFrame(list)
df

0
40

,Time,Temp,Pressure,Ground_level,Humidity,Cloud_description,Wind,Wind_direction,Visibility,Rain
0,2022-06-24 14:30:00,37.05,1003,975,25,clear sky,4.06,303,10000,None
1,2022-06-24 17:30:00,38.38,1001,973,19,clear sky,4.57,310,10000,None
2,2022-06-24 20:30:00,38.26,1000,974,15,clear sky,3.54,301,10000,None
3,2022-06-24 23:30:00,36.60,998,974,13,clear sky,2.74,293,10000,None
4,2022-06-25 02:30:00,34.91,998,974,17,clear sky,2.83,282,10000,None
5,2022-06-25 05:30:00,33.62,998,974,21,clear sky,2.11,308,10000,None
6,2022-06-25 08:30:00,36.55,999,975,16,clear sky,2.77,328,10000,None
7,2022-06-25 11:30:00,41.29,998,975,10,clear sky,0.79,305,10000,None
8,2022-06-25 14:30:00,42.70,996,972,8,clear sky,1.98,230,10000,None
9,2022-06-25 17:30:00,42.73,995,971,7,clear sky,1.32,246,10000,None
10,2022-06-25 20:30:00,40.99,995,972,8,clear sky,1.27,300,10000,None
11,2022-06-25 23:30:00,38.55,996,972,16,clear sky,3.01,300,10000,None
12,2022-06-26 02:30:00,37.27,996,972,17,clear sky,1.73,319,10000,None
13,2022-06-26 05:30:00,35.33,997,973,17,scattered clouds,2.86,68,10000,None
14,2022-06-26 08:30:00,37.35,999,975,30,clear sky,4.98,114,10000,None
15,2022-06-26 11:30:00,42.47,998,974,18,clear sky,2.03,109,10000,None
16,2022-06-26 14:30:00,44.24,996,972,13,clear sky,1.34,250,10000,None
17,2022-06-26 17:30:00,44.19,995,971,13,few clouds,1.62,272,10000,None
18,2022-06-26 20:30:00,42.57,996,972,13,scattered clouds,0.30,195,10000,None
19,2022-06-26 23:30:00,37.63,998,974,37,broken clouds,6.41,136,10000,None
20,2022-06-27 02:30:00,35.64,998,974,44,broken clouds,5.87,124,10000,None
21,2022-06-27 05:30:00,34.68,999,975,45,broken clouds,5.42,122,10000,None
22,2022-06-27 08:30:00,35.06,1001,977,45,scattered clouds,5.56,119,10000,None
23,2022-06-27 11:30:00,39.48,1000,976,33,scattered clouds,3.96,141,10000,None
24,2022-06-27 14:30:00,43.26,997,973,21,few clouds,2.06,130,10000,None
25,2022-06-27 17:30:00,43.56,995,972,19,few clouds,1.28,77,10000,None
26,2022-06-27 20:30:00,40.42,996,972,28,broken clouds,5.60,113,10000,None
27,2022-06-27 23:30:00,37.25,998,974,40,broken clouds,7.06,130,10000,None
28,2022-06-28 02:30:00,34.93,997,973,47,overcast clouds,6.02,131,10000,None
29,2022-06-28 05:30:00,33.40,998,974,51,overcast clouds,5.58,113,10000,None
30,2022-06-28 08:30:00,34.57,998,974,47,scattered clouds,5.64,129,10000,None
31,2022-06-28 11:30:00,40.45,997,973,31,broken clouds,3.48,144,10000,None
32,2022-06-28 14:30:00,44.90,994,970,19,overcast clouds,0.85,191,10000,None
33,2022-06-28 17:30:00,44.80,991,968,17,broken clouds,1.10,107,10000,None
34,2022-06-28 20:30:00,42.82,992,969,20,broken clouds,3.40,79,10000,None
35,2022-06-28 23:30:00,38.63,994,970,34,broken clouds,6.04,115,10000,None
36,2022-06-29 02:30:00,36.65,993,969,40,overcast clouds,6.14,137,10000,None
37,2022-06-29 05:30:00,34.53,994,970,47,overcast clouds,4.97,130,10000,None
38,2022-06-29 08:30:00,35.92,995,971,43,scattered clouds,3.31,132,10000,None
39,2022-06-29 11:30:00,40.75,994,970,29,few clouds,1.42,86,10000,None